"""Manual, one-shot swap of a subscription's vendor, for its REMAINING term.

Ops-triggered operation: moves an already-provisioned subscription from its current
vendor to another one (e.g. artemida -> a future second vendor) without touching the
client's link. The link survives because ``Subscription.public_token`` is stable and
never regenerated by ``provision`` — each vendor's ``provision`` rebuilds
``subscription_url`` from that same token, so the URL the client already has keeps
working after the swap.

Not wired into any scheduled job or webhook: this is a deliberate, manual action an
operator takes on a single subscription (e.g. a vendor is unwell and its subscriptions
need to move off it), not an automatic failover.
"""

from datetime import UTC, datetime
from types import SimpleNamespace

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

from app.database.models import Subscription, _aware
from app.services.providers import get_provider_by_name


logger = structlog.get_logger(__name__)


class ProviderSwapError(Exception):
    """Raised when a manual vendor swap cannot proceed (unknown/unsupported target)."""


async def move_subscription_to_provider(
    db: AsyncSession,
    subscription: Subscription,
    new_provider_name: str,
    *,
    bot=None,
) -> None:
    """Move ``subscription`` onto ``new_provider_name`` for its remaining term.

    On success: the NEW vendor is provisioned for the days left until
    ``subscription.end_date``, ``subscription.subscription_url`` stays byte-identical
    (rebuilt from the unchanged ``public_token``), and the OLD vendor key is revoked
    best-effort (a failed revoke never fails the swap — see the note below).

    On failure: if provisioning the NEW vendor raises, nothing is touched and the
    exception is re-raised as-is — the subscription is still served by the OLD vendor,
    unchanged.

    ``bot`` is accepted (unused for now) so a future revision can notify the operator
    without changing this function's call sites.
    """
    new_provider = get_provider_by_name(new_provider_name)
    if new_provider is None or new_provider.name == 'remnawave':
        raise ProviderSwapError(f'Unknown or unsupported target provider: {new_provider_name!r}')

    if subscription.external_provider == new_provider_name:
        return  # already on the target vendor — nothing to do

    # Captured BEFORE anything changes: provision() below overwrites both fields with
    # the NEW vendor's values, so this is the only chance to remember the OLD ones.
    old_name = subscription.external_provider
    old_ref = subscription.external_ref

    end = _aware(subscription.end_date)
    days = max(1, (end - datetime.now(UTC)).days) if end is not None else 1

    # provision() reads subscription.tariff.device_limit; the relation may not be
    # loaded on whatever Subscription instance the caller handed in.
    try:
        await db.refresh(subscription, ['tariff'])
    except Exception:
        pass

    # If this raises, do NOT touch anything else below — re-raise as-is. The
    # subscription is still fully served by the OLD vendor at this point.
    await new_provider.provision(db=db, subscription=subscription, days=days)
    await db.commit()

    # Best-effort revoke of the OLD vendor key. subscription.external_ref now holds the
    # NEW key (provision() overwrote it), so a minimal shim carrying the OLD ref stands
    # in for the subscription the old provider's revoke() expects.
    #
    # NOTE: revoke()'s idempotency key is `sub-{id}-revoke`, scoped to the subscription
    # id, not to the vendor ref. A SECOND swap of the same subscription would reuse that
    # same key and would NOT actually revoke the second old key at the vendor — a known
    # limitation for repeated swaps. The un-revoked old key auto-expires on its own, so
    # this is acceptable for a rare manual op; a follow-up could key revoke on the ref
    # instead of the subscription id.
    old_provider = get_provider_by_name(old_name)
    if old_provider is not None and old_provider.name != 'remnawave' and old_ref:
        old_sub = SimpleNamespace(id=subscription.id, external_ref=old_ref)
        try:
            await old_provider.revoke(db=db, subscription=old_sub)
        except Exception as e:
            logger.warning(
                'swap: старый ключ не отозван (протухнет сам)',
                subscription_id=subscription.id,
                old_provider=old_name,
                error=str(e),
            )
        else:
            logger.info(
                'Старый ключ вендора отозван после свопа',
                subscription_id=subscription.id,
                old_provider=old_name,
            )

    logger.info(
        'Подписка переключена на другого вендора',
        subscription_id=subscription.id,
        old=old_name,
        new=new_provider_name,
    )
